[application]
name = "Mango³ Drive"

[web.app]

# HTML title tag content
title = "Mango³ Drive"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
identifier = "app.mango3.drive"
